# Generated by Django 3.2 on 2024-05-13 07:55

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_document_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=chat.models.document_directory_path),
        ),
    ]
